trigger:
- main

pool:
  MylocalPool
  #vmImage: ubuntu-latest
  #MylocalPool
  
variables:
  LT_USERNAME: 'ankitclambdatest' 
  LT_ACCESS_KEY: 'LT_OnEL30AtoPH0BkcY83K0VnpQOcfFpX71axsfQgHGLhvNfUP' 
  LT_BUILD_NAME: 'Azure_testng_demo'

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTestJob
    steps:
      - task: configuration@1
        inputs:
            connection: 'ankit-LT-connection'
            #isTunnelActivate: true
            #tunnelOptions: '{"tunnelName": "ABC"}'
      - script: |
          mvn clean install -DskipTests
      - script: "mvn test -D suite=single.xml"
        displayName: "Command Line Script"
      - task: LambdatestResults@1
        
# - stage: LambdatestResults
#   jobs:
#   - job: LambdatestResultsJob
#     steps:
#       - script: |
#           echo "Hello"